file:
  upload-path: D:/SGAME/upload

spring:
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  endPoint: http://43.137.12.232:9000
  accessKey: admin
  secretKey: admin123
