spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      password:     #默认为空
      lettuce:
        pool:
          min-idle: 10 #连接池中的最小空闲数.默认为 0
          max-idle: 20 #连接池中的最大空闲数,默认为 8
          max-active: 100 #连接池的最大连接数,默认为 8
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
   username: root
   password: password
   driver-class-name: com.mysql.cj.jdbc.Driver
guke:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9035ff9f0192adc269b97ca7
      accountToken: ebf63a76505c48b3b7d93405928f0397
      appId: 2c94811c9035ff9f0192adc26b3a7cae
      templateId: 1

logging:
  level:
    com.baomidou.mybatisplus.samples: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  global-config:
   db-config:
     logic-delete-field: deleted
     logic-delete-value: 1
     logic-not-delete-value: 0


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.guke.springboot.redis.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456
