spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      hbm2ddl:
       auto: update
    dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      spring.jackson.date-format: yyyy-MM-dd HH:mm  # 配置日期格式
      spring.jackson.serialization.write-dates-as-timestamps: false  # 禁用时间戳格式


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

aliyun:
  oss:
    endpoint: https://oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5tGCiRt1EPPc3BkUKZn6
    accessKeySecret: 264CwMuMlJXVZqKJ4ptqQktLIhOjEz
    bucketName: guke-bucket
